#!/bin/sh
#
# `::: bigwidetable`でマークアップされた表に、特別な書式を設定するためのフィルター
#
awk '
{
    if ($0 ~ /^:::\s+bigwidetable\s*$/) {
        print "\\begingroup"
        print "\\footnotesize"
        print "\\renewcommand{\\arraystretch}{0.8}"
    } else if ($0 ~ /^:::\s*$/) {
        print "\\endgroup"
        print ""
    } else {
        print $0
    }
}
'
