from: markdown+fenced_divs+lists_without_preceding_blankline
toc: true
lot: true
toc-depth: 2
template: ./templates/main.tex
variables:
    colorlinks: true
    linkcolor: blue
    urlcolor: red
    toccolor: blue
metadata:
    documentclass: bxjsarticle
    geometry: a4paper, margin=20mm
