pdf-engine: lualatex
variables:
    lang: ja
    documentclass: ltjsarticle
    luatexjapresetoptions: fonts-noto-cjk
include-in-header:
    - ./headers/headers.tex
metadata:
    documentclass: bxjsarticle
    geometry: a4paper, margin=20mm
    title: ディスクゴルフ大会のための競技マニュアル
    subtitle:
        - 2024年版
    author: Professional Disc Golf Association
    date: 2014年11月11日
    copyright: The original copyright of this book is reserved by PDGA®.
    publisher: 静岡県ディスクゴルフ協会
    contact: jpdga.shizuoka@gmail.com
