pdf-engine: lualatex
variables:
    lang: ja
    luatexjapresetoptions: fonts-noto-cjk
include-in-header:
    - ./headers/headers.tex
metadata:
    documentclass: ltjsarticle
    classoption: twoside
    geometry: a4paper, margin=20mm
    title: ディスクゴルフ大会のための競技マニュアル
    author: Professional Disc Golf Association
    copyright: The original copyright of this book is reserved by PDGA®.
    publisher: 静岡県ディスクゴルフ協会
    contact: jpdga.shizuoka@gmail.com
